## Chapter1

In [60]:
import torch

###宣告tenser並輸出

In [61]:
z = torch.Tensor(4,5) #()內放維度
z #輸出z輸出z 
#由list形成的list

tensor([[2.9733e-29, 3.0739e-41, 7.0065e-44, 6.8664e-44, 6.3058e-44],
        [6.7262e-44, 7.9874e-44, 6.3058e-44, 7.0065e-44, 6.8664e-44],
        [1.1771e-43, 6.7262e-44, 7.8473e-44, 8.1275e-44, 7.4269e-44],
        [7.2868e-44, 8.1275e-44, 6.8664e-44, 7.9874e-44, 6.4460e-44]])

###tenser dtype(data type)

In [62]:
z.dtype

torch.float32

###宣告不同type的tenser

torch.IntTensor

torch.FloatTensor


In [63]:
a = torch.FloatTensor(4,5)
b = torch.FloatTensor([[2,3], [4,5]]) 
a

tensor([[2.9730e-29, 3.0739e-41, 7.0065e-44, 6.8664e-44, 6.3058e-44],
        [6.7262e-44, 7.9874e-44, 6.3058e-44, 7.0065e-44, 6.8664e-44],
        [1.1771e-43, 6.7262e-44, 7.8473e-44, 8.1275e-44, 7.4269e-44],
        [7.2868e-44, 8.1275e-44, 6.8664e-44, 7.9874e-44, 6.4460e-44]])

In [64]:
b

tensor([[2., 3.],
        [4., 5.]])

In [65]:
a = torch.IntTensor(4,5)
b = torch.FloatTensor([[2,3], [4,5]]) 
a

tensor([[269931392,     21936,        50,        49,        45],
        [       48,        57,        45,        50,        49],
        [       84,        48,        56,        58,        53],
        [       52,        58,        49,        57,        46]],
       dtype=torch.int32)

In [66]:
b

tensor([[2., 3.],
        [4., 5.]])

### tenser做運算

In [67]:
y = a + z 
y

tensor([[2.6993e+08, 2.1936e+04, 5.0000e+01, 4.9000e+01, 4.5000e+01],
        [4.8000e+01, 5.7000e+01, 4.5000e+01, 5.0000e+01, 4.9000e+01],
        [8.4000e+01, 4.8000e+01, 5.6000e+01, 5.8000e+01, 5.3000e+01],
        [5.2000e+01, 5.8000e+01, 4.9000e+01, 5.7000e+01, 4.6000e+01]])

In [68]:
y.dtype #會自動轉型成較高精度

torch.float32

In [69]:
torch.add(z, a) #陣列相加or陣列加純量

tensor([[2.6993e+08, 2.1936e+04, 5.0000e+01, 4.9000e+01, 4.5000e+01],
        [4.8000e+01, 5.7000e+01, 4.5000e+01, 5.0000e+01, 4.9000e+01],
        [8.4000e+01, 4.8000e+01, 5.6000e+01, 5.8000e+01, 5.3000e+01],
        [5.2000e+01, 5.8000e+01, 4.9000e+01, 5.7000e+01, 4.6000e+01]])

###rand

In [70]:
a = torch.rand(4, 5)
a

tensor([[0.6221, 0.7416, 0.4135, 0.2591, 0.0380],
        [0.7272, 0.6148, 0.3706, 0.9197, 0.8996],
        [0.3402, 0.5251, 0.3491, 0.2051, 0.9460],
        [0.9935, 0.8928, 0.6171, 0.3246, 0.4526]])

In [71]:
a.dtype

torch.float32

###將tenser轉np的array

In [72]:
import numpy as np #縮寫為np

In [73]:
b = a.numpy()
b

array([[0.62214273, 0.7416076 , 0.41351748, 0.25906044, 0.03802961],
       [0.7271618 , 0.6147626 , 0.37059677, 0.9196961 , 0.89957637],
       [0.34019846, 0.5251321 , 0.3491125 , 0.20508957, 0.9460395 ],
       [0.99353004, 0.8927698 , 0.61711836, 0.32457733, 0.45259863]],
      dtype=float32)

###將np array轉tenser (torch.from_numpy())
#### ★須注意型態

In [74]:
a = np.ones(5)  #全部都是1的一維陣列
b = torch.from_numpy(a)
a

array([1., 1., 1., 1., 1.])

In [75]:
b #型態為folat64和平常torch內的float32型態不同

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [76]:
np.add(a, 1, out= a) #out:輸出結果到a
a

array([2., 2., 2., 2., 2.])

In [77]:
b #b也跟著變
#將arrayt傳到tenser時是傳reference(O.O的概念)
#有些運算tenser無法做->先轉成numpy操作

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [78]:
c = b + torch.FloatTensor([1,2,3,4,5])
c 

tensor([3., 4., 5., 6., 7.], dtype=torch.float64)

#### tenser轉型

In [79]:
c = c.float() #將float64轉成float32
c.dtype

torch.float32

In [80]:
c = c.double() #將float32轉float64
c.dtype

torch.float64

In [81]:
c = c.int()
c.dtype

torch.int32


### size、torch.squeeze()

In [82]:
x = torch.zeros(2,1,2,1,2) #產生全0的陣列
x.size()

torch.Size([2, 1, 2, 1, 2])

In [83]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [84]:
y = torch.squeeze(x) #消掉多餘維度
y.size()

torch.Size([2, 2, 2])

In [85]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [86]:
y = torch.squeeze(x,0) #可指定squeeze的index(如果可壓縮)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [87]:
y = torch.squeeze(x,1) #可指定squeeze的index(如果可壓縮)
y.size()

torch.Size([2, 2, 1, 2])

In [88]:
y = torch.squeeze(y, 2) #注意前面若squeeze後，index會改變
y.size()

torch.Size([2, 2, 2])

### abs(取絕對值)


In [89]:
torch.abs(torch.FloatTensor([-1,-2,3]))

tensor([1., 2., 3.])

### randn(有正、負數的rand)

In [90]:
a = torch.randn(4)
a

tensor([ 0.3770, -0.3613,  0.4264,  1.8509])

In [91]:
b = torch.add(a, 20)
b

tensor([20.3770, 19.6387, 20.4264, 21.8509])

#### 每一項相乘

In [92]:
c = torch.mul(a, 0.1)
c

tensor([ 0.0377, -0.0361,  0.0426,  0.1851])

In [93]:
d = torch.mul(a, b) 
d

tensor([ 7.6820, -7.0949,  8.7108, 40.4445])

#### matrix相乘(2維)
torch.matmul(x,y)

PS:高維度沒有定義矩陣乘法




In [94]:
x = torch.rand(2,3)
y = torch.rand(3,2)
x

tensor([[0.7876, 0.0530, 0.0670],
        [0.0360, 0.7334, 0.7291]])

In [95]:
y

tensor([[0.2884, 0.3047],
        [0.7243, 0.0769],
        [0.1990, 0.9199]])

In [96]:
d = torch.matmul(x,y)
d

tensor([[0.2789, 0.3056],
        [0.6867, 0.7380]])

In [97]:
e = torch.matmul(y,x)
e

tensor([[0.2381, 0.2388, 0.2414],
        [0.5732, 0.0948, 0.1046],
        [0.1899, 0.6852, 0.6840]])

### mean

In [98]:
y.size()

torch.Size([3, 2])

In [99]:
#方法一
k = y.mean() #結果是tenser的物件而非純量
k.data #只取裡面的值

tensor(0.4189)

In [100]:
#方法二
torch.mean(y)

tensor(0.4189)

In [101]:
torch.mean(y,0) #以某個維度的角度做平均 0做vector->3個向量

tensor([0.4039, 0.4338])

In [102]:
torch.mean(y,1) #以某個維度的角度做平均 1做vector->2個向量

tensor([0.2965, 0.4006, 0.5595])

### compare

In [103]:
x = torch.Tensor([[1,2],[3,4]])
y = torch.Tensor([[1,1],[4,4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [104]:
y

tensor([[1., 1.],
        [4., 4.]])

#### 比較兩個矩陣的對應內容



In [105]:
torch.eq(x,y) #前提要格式相同

tensor([[ True, False],
        [False,  True]])

#### 比較兩矩陣是否相同

In [106]:
torch.equal(y,y)

True

#### ge : >=
#### le : <=
#### gt : >
#### lt : <

In [107]:
torch.ge(x,y) #ge(greater than or equal):>=

tensor([[ True,  True],
        [False,  True]])

In [108]:
torch.le(x,y) #le:<=

tensor([[ True, False],
        [ True,  True]])

In [109]:
torch.gt(x,y)

tensor([[False,  True],
        [False, False]])

In [110]:
torch.lt(x,y)

tensor([[False, False],
        [ True, False]])